// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";

function simple(param) {
  var resolve = function (data) {
    console.log(data);
    
  };
  var reject = function (param) {
    console.log("code", param[0]);
    console.log("msg", param[1]);
    
  };
  var onCancel = function (param) {
    console.log("request canceled");
    
  };
  console.log("simpleRequest start...");
  Api.getBikes(resolve, reject, onCancel, undefined);
  
}

function simpleCanceled(param) {
  var resolve = function (data) {
    console.log(data);
    
  };
  var reject = function (param) {
    console.log("code", param[0]);
    console.log("msg", param[1]);
    
  };
  var onCancel = function (param) {
    console.log("request canceled");
    
  };
  console.log("simpleRequestCanceled start...");
  var cancel = Api.getBikes(resolve, reject, onCancel, undefined);
  return Curry._1(cancel, undefined);
}

export {
  simple ,
  simpleCanceled ,
  
}
/* No side effect */
