// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SequentialRequest from "./SequentialRequest.js";

SequentialRequest.sequential((function (data) {
          console.log("seq data", data);
          
        }), (function (param) {
          console.log("failed");
          
        }), undefined)(undefined);

export {
  
}
/*  Not a pure module */
